### ISSUE TITLE
Can you support adding friends and online on That Sky Mod V2.0 (Sky V26.3)

### ISSUE THREAD

**Issue by NingMengSuDa** [TheSR007/That_Sky_Mod_Release#5]

**Comment by TheSR007** [comment]
I don't maintain TSM anymore and Lukas will maintain V2.0,
That being said the feature is already implemented and it should work in official server, as for private server it doesn't work because the certificate in not trusted by curl, so wait for TGC to implement the private server for us and get in touch with Lukas for further assistance
